### ISSUE TITLE
Initial setting

### ISSUE THREAD

**Issue by luisdemarchi** [USAN/res_speech_gdfe#17]
Hello,
Thank you very much for sharing this project, for the description is exactly what I was looking for. But I'm confused how to do the initial configuration, in your build.sh file is a build to create asterisk from zero, right?

**Comment by DanDanN00dle** [comment]
Yes, the build script in this project will build a demo asterisk from scratch. Replicate the steps in your source tree if you want to integrate to a different asterisk build.
