### ISSUE TITLE
The call is simply terminated

### ISSUE THREAD

**Issue by luisdemarchi** [USAN/res_speech_gdfe#18]
I am using Microsoft TTS successfully, but when it arrives in your "SpeechBackground" function, the connection is simply terminated. I activated the DialogFlow Enterprise Edition Essentials account.

Follow log:

>   == Setting global variable 'SIPDOMAIN' to 'MY_IP_STATIC'
>     -- Executing [5000@ramais:1] Goto("PJSIP/6001-00000001", "dialogflow,s,1") in new stack
>     -- Goto (dialogflow,s,1)
>     -- Executing [s@dialogflow:1] NoOp("PJSIP/6001-00000001", "Dialogflow") in new stack
>     -- Executing [s@dialogflow:2] Answer("PJSIP/6001-00000001", "") in new stack
>        > 0x7fb380012340 -- Strict RTP learning after remote address set to: IP:47634
>        > 0x7fb380012340 -- Strict RTP switching to RTP target address IP:47634 as source
>     -- Executing [s@dialogflow:3] SpeechCreate("PJSIP/6001-00000001", "") in new stack
>     -- Executing [s@dialogflow:4] Set("PJSIP/6001-00000001", "LANG_OVERRIDE=") in new stack
>     -- Executing [s@dialogflow:5] Set("PJSIP/6001-00000001", "SPEECH_ENGINE(project_id)=DIALOGFLOW_ID") in new stack
>     -- Executing [s@dialogflow:6] Set("PJSIP/6001-00000001", "SPEECH_ENGINE(session_id)=2332") in new stack
>     -- Executing [s@dialogflow:7] Set("PJSIP/6001-00000001", "SPEECH_ENGINE(language)=pt-BR") in new stack
>     -- Executing [s@dialogflow:8] GotoIf("PJSIP/6001-00000001", "1?clear_prompt") in new stack
>     -- Goto (dialogflow,s,10)
>     -- Executing [s@dialogflow:10] Set("PJSIP/6001-00000001", "PROMPT=hello-world") in new stack

>     -- Executing [s@dialogflow:11] AGI("PJSIP/6001-00000001", "mstts.agi,"Olá Luís.",pt-BR") in new stack
>     -- Launched AGI Script /var/lib/asterisk/agi-bin/mstts.agi
>     -- <PJSIP/6001-00000001> Playing '/tmp/2ad266c68b0c72f0baafcb84dc6c9054.slin16' (escape_digits=) (sample_offset 0) (language 'en')

>     -- <PJSIP/6001-00000001>AGI Script mstts.agi completed, returning 0
>     -- Executing [s@dialogflow:12] SpeechBackground("PJSIP/6001-00000001", "hello-world") in new stack
>   == Spawn extension (dialogflow, s, 12) exited non-zero on 'PJSIP/6001-00000001'
>

**Comment by DanDanN00dle** [comment]
Can you provide a full log excerpt? It should provide some information as to why the call is terminating. You may need to turn up core debug.
