### ISSUE TITLE
Problem compiling asterisk using  res_speech_gdfe

### ISSUE THREAD

**Issue by mdominguezh** [USAN/res_speech_gdfe#25]
Hi,

I could compile using  res_speech_gdfe without problems, but when I try to compile asterisk ( asterisk-certified-13.21-cert or asterisk-13.21.1 ) using  res_speech_gdfe I get some errors. 
[error_res_speech_gdfe.txt](https://github.com/USAN/res_speech_gdfe/files/3077949/error_res_speech_gdfe.txt).

Can you help me to solve this problem?. Thanks in advance. 

Best Regards.

**Comment by DanDanN00dle** [comment]
Fixed in pull #27
