### ISSUE TITLE
Install on running asterisk

### ISSUE THREAD

**Issue by mkasprzycki** [USAN/res_speech_gdfe#36]
Hi 

I download all files, res files add to res folder in asterisk but when I compile asterisk there are no SO files for your C files
Can you make tutorial how to install?

**Comment by DanDanN00dle** [comment]
Please see `build.sh`. There is additional patching of the configure scripts & asterisk build files that must be done so asterisk is aware of the new files.

There are also additional dependencies above and beyond just these res files that must be downloaded and compiled first.

**Comment by mkasprzycki** [comment]
Hi I used build.sh asterisk install successfully but after few minutes shutdown with

res_metering.c:207 send_metric_data: Got error 0 posting metric to http://localhost:4242/report -- Couldn't connect to server
ERROR[8624]: res_metering.c:95 stop_asterisk: Shutting down asterisk due to metering failures.

**Comment by DanDanN00dle** [comment]
You can `noload` that module.
